export type Project = {
  caseStudySlug?: string;
  engagement: string;
  industrySlug: string;
  logo: string;
  name: string;
  stage: string;
  summary: string;
  vertical: string;
};

export const projects: Project[] = [
  {
    caseStudySlug: "facilitating-scisports-growth-through-acquisition",
    engagement: "M&A advisory",
    industrySlug: "digital-technology",
    logo: "/images/clients/scisports.svg",
    name: "SciSports",
    stage: "Strategic acquisition",
    summary:
      "AI-driven football analytics that turn live performance data into actionable sporting intelligence.",
    vertical: "AI & Sports Analytics",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/moos.png",
    name: "MOOS",
    stage: "Seed / acquisition",
    summary:
      "AI-powered shelf sensors providing real-time inventory visibility across retail and healthcare.",
    vertical: "AI & Sensor Tech",
  },
  {
    engagement: "Commercial due diligence",
    industrySlug: "digital-technology",
    logo: "/images/clients/infraspeak.svg",
    name: "Infraspeak",
    stage: "Series B",
    summary:
      "An intelligent maintenance platform helping facilities teams coordinate operations and make better decisions.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Commercial due diligence",
    industrySlug: "digital-technology",
    logo: "/images/clients/fairly-made.svg",
    name: "Fairly Made",
    stage: "Series B",
    summary:
      "A sustainability platform helping fashion brands measure and improve their environmental impact.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/barion.svg",
    name: "Barion",
    stage: "Series B",
    summary: "Smart payment infrastructure for online and in-store commerce.",
    vertical: "FinTech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/owlin.png",
    name: "Owlin",
    stage: "Series B",
    summary:
      "AI-powered risk intelligence that monitors global news and data sources in real time.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/moreapp.svg",
    name: "MoreApp",
    stage: "Series B",
    summary: "Digital forms that help field teams replace paperwork with structured workflows.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/maqqie.png",
    name: "Maqqie",
    stage: "Series B",
    summary: "A platform simplifying flexible workforce management for companies and contractors.",
    vertical: "HRTech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/telkey.png",
    name: "Telkey",
    stage: "Series A",
    summary: "Smart access technology enabling secure digital key distribution and remote control.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/easy2audit.png",
    name: "Easy2Audit",
    stage: "Series A",
    summary: "Intelligent automation that streamlines audit workflows for accounting firms.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/vialuxury.svg",
    name: "ViaLuxury",
    stage: "Series A",
    summary: "A digital platform connecting consumers with curated premium travel experiences.",
    vertical: "Travel Tech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/datylon.svg",
    name: "Datylon",
    stage: "Series A",
    summary:
      "Professional data visualisation and chart-design tools for clear visual communication.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "digital-technology",
    logo: "/images/clients/omrt.png",
    name: "OMRT",
    stage: "Seed",
    summary: "Parametric software transforming computational design for real-estate development.",
    vertical: "Digital Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/spark.png",
    name: "SPARK",
    stage: "Series B",
    summary: "Solar-powered battery systems that store clean energy for use after sunset.",
    vertical: "Battery Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/blue-heart-energy.png",
    name: "Blue Heart Energy",
    stage: "Series A",
    summary:
      "Thermoacoustic technology using sound waves to provide efficient heating and cooling.",
    vertical: "HVAC Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/viride.png",
    name: "Viride",
    stage: "Series A",
    summary:
      "Clean-technology solutions supporting industrial decarbonisation and resource efficiency.",
    vertical: "FoodTech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/tarnoc.svg",
    name: "Tarnoc",
    stage: "Seed",
    summary: "A patented turbine heat pump designed for high-temperature, fossil-free heating.",
    vertical: "HVAC Technology",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/kitepower.png",
    name: "Kitepower",
    stage: "Seed",
    summary: "Airborne wind-energy systems generating clean electricity with automated kites.",
    vertical: "Energy & Sustainability",
  },
  {
    engagement: "Fundraising",
    industrySlug: "energy-and-sustainability",
    logo: "/images/clients/evert.svg",
    name: "Evert",
    stage: "Seed",
    summary:
      "Smart energy-management technology optimising energy use for businesses and consumers.",
    vertical: "Energy & Sustainability",
  },
  {
    engagement: "Fundraising",
    industrySlug: "food-and-agri",
    logo: "/images/clients/precitaste.png",
    name: "PreciTaste",
    stage: "Series A",
    summary: "AI-powered restaurant software improving demand forecasting and kitchen operations.",
    vertical: "FoodTech & AI",
  },
  {
    engagement: "Fundraising",
    industrySlug: "food-and-agri",
    logo: "/images/clients/junea.svg",
    name: "Junea",
    stage: "Series A",
    summary: "Smart vending that combines connected hardware with intelligent retail software.",
    vertical: "Smart Vending",
  },
  {
    caseStudySlug: "providing-collie-with-end-to-end-fundraising-support",
    engagement: "Fundraising",
    industrySlug: "food-and-agri",
    logo: "/images/clients/collie.png",
    name: "Collie",
    stage: "Seed",
    summary: "Virtual fencing and cow-guidance technology for more sustainable dairy farming.",
    vertical: "AgriTech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "food-and-agri",
    logo: "/images/clients/earthrover.webp",
    name: "Earthrover",
    stage: "Seed",
    summary: "Autonomous agricultural robots using AI and computer vision for precision farming.",
    vertical: "AgriTech & Robotics",
  },
  {
    engagement: "M&A advisory",
    industrySlug: "mobility-and-aerospace",
    logo: "/images/clients/horus.png",
    name: "Horus",
    stage: "Strategic acquisition",
    summary:
      "Adaptive mapping technology turning vehicles into intelligent spatial-computing platforms.",
    vertical: "Mobility & Mapping",
  },
  {
    engagement: "Fundraising",
    industrySlug: "mobility-and-aerospace",
    logo: "/images/clients/dockr.svg",
    name: "DOCKR",
    stage: "Series A",
    summary: "Electric last-mile delivery vehicles offered through flexible fleet solutions.",
    vertical: "Mobility & Sustainability",
  },
  {
    engagement: "Fundraising",
    industrySlug: "mobility-and-aerospace",
    logo: "/images/clients/stilride.png",
    name: "Stilride / STILFOLD",
    stage: "Seed",
    summary:
      "Industrial-origami manufacturing enabling lighter and more sustainable mobility products.",
    vertical: "Mobility & Aerospace",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/incus-3d.svg",
    name: "Incus 3D",
    stage: "Series B",
    summary:
      "Industrial metal additive manufacturing based on lithography-based metal manufacturing.",
    vertical: "Additive Manufacturing",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/inphocal.png",
    name: "inPhocal",
    stage: "Series A",
    summary: "CERN-derived laser technology delivering high-precision optical processing at scale.",
    vertical: "Photonics",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/recell.svg",
    name: "Recell",
    stage: "Series A",
    summary:
      "Technology converting discarded cellulosic waste into next-generation industrial resources.",
    vertical: "Biotech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/solid-3d.png",
    name: "{Solid}3D",
    stage: "Series A",
    summary:
      "Robotics accelerating the transition to automated warehouses and manufacturing facilities.",
    vertical: "Robotics",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/am-flow.png",
    name: "AM-Flow",
    stage: "Series A",
    summary:
      "AI-powered automation for identification, sorting and routing in additive manufacturing.",
    vertical: "Advanced Manufacturing",
  },
  {
    engagement: "Fundraising",
    industrySlug: "advanced-materials-and-manufacturing",
    logo: "/images/clients/co2bioclean.png",
    name: "CO2BioClean",
    stage: "Seed",
    summary:
      "Fermentation technology converting carbon emissions into natural, fossil-free biopolymers.",
    vertical: "Advanced Materials",
  },
  {
    engagement: "Fundraising",
    industrySlug: "health-and-life-sciences",
    logo: "/images/clients/alfarim.png",
    name: "Alfarim",
    stage: "Series A",
    summary:
      "Industrial production of actinium-225 for next-generation targeted cancer treatments.",
    vertical: "Health & Life Sciences",
  },
  {
    engagement: "Fundraising",
    industrySlug: "health-and-life-sciences",
    logo: "/images/clients/vitadio.svg",
    name: "Vitadio",
    stage: "Series A",
    summary: "AI-powered digital therapeutics supporting people living with diabetes.",
    vertical: "Digital Therapeutics",
  },
  {
    engagement: "Fundraising",
    industrySlug: "health-and-life-sciences",
    logo: "/images/clients/prosoma.svg",
    name: "Prosoma",
    stage: "Series A",
    summary:
      "Digital-health programmes combining clinical expertise with patient-centred technology.",
    vertical: "HealthTech",
  },
  {
    engagement: "Fundraising",
    industrySlug: "health-and-life-sciences",
    logo: "/images/clients/perivision.png",
    name: "Perivision",
    stage: "Series A",
    summary: "Advanced ophthalmic diagnostics improving access to precise eye-care testing.",
    vertical: "Health & Life Sciences",
  },
  {
    engagement: "Fundraising",
    industrySlug: "health-and-life-sciences",
    logo: "/images/clients/corelife-analytics.svg",
    name: "CoreLife Analytics",
    stage: "Series A",
    summary:
      "Advanced analytics helping life-science teams accelerate drug discovery and development.",
    vertical: "AI-Driven Drug Discovery",
  },
];

export const projectsForIndustry = (industrySlug: string) =>
  projects.filter((project) => project.industrySlug === industrySlug);
